### ISSUE TITLE
Feature request: alerts limiting

### ISSUE THREAD

**Issue by LM1LC3N7** [Leproide/LINUX-Telegram-TEMP-alert#1]
Hi!

Thanks for the project, simple but effective!
I notice that in case the temperature is above the threshold, we get a message every 5 seconds (timer default value).
You could add a mechanism to avoid receiving an alert message every 5 seconds in case of alerts. Like sending a message once, and then sending a message every hours like "temperature warning still ongoing".
After the temperature is going down, you also could send a message "temperature alert finished".

**Comment by Leproide** [comment]
Hi LM1LC3N7 :)
Yep, try this:

```bash
#! /bin/bash

telegrambot="*your_api_key"
telegramchatid="your_chat_ID"
url="https://api.telegram.org/bot$telegrambot/sendMessage"

# Threshold for when to send alert (80°)
threshold=80

# File to track alert state
alert_file="/tmp/alert_sent"

sensors | grep "Package id 0:" | while read -r line; do
    temp=$(echo "$line" | awk -F "+" '{ print $2 }' | awk -F "." '{ print $1 }');
    if ((temp > threshold)); then
        if [ ! -f "$alert_file" ]; then
            message="TEMP ALERT for $(hostname). Temperature is $temp degrees"
            curl -s -d "chat_id=$telegramchatid&text=$message&parse_mode=markdown&disable_web_page_preview=1" "$url" > /dev/null 2>&1
            touch "$alert_file"  # Create the alert file after sending the alert
        fi
    else
        if [ -f "$alert_file" ]; then
            # Send a message when temperature goes below the threshold
            message="Temperature has returned below the alert threshold on $(hostname)."
            curl -s -d "chat_id=$telegramchatid&text=$message&parse_mode=markdown&disable_web_page_preview=1" "$url" > /dev/null 2>&1
            rm "$alert_file"  # Remove the alert file if temperature is below threshold
        fi
    fi
done
```

**Comment by LM1LC3N7** [comment]
Sounds good, will try it soon. Thanks a lot 🤩

**Comment by Leproide** [comment]
Np :)
Check that the script can write to temp.
if it cannot, it won't be able to create the temporary file.

Now If temp is above the threshold:
If the alert_file does not exist (meaning no alert has been sent yet), a Telegram message is created with the temperature and sent via curl.
Then, alert_file is created to prevent repeated alerts.

If temp falls below the threshold:
If alert_file exists (meaning an alert was previously sent), a Telegram message is sent to inform that the temperature has returned to normal, and alert_file is deleted.

This way, the system avoids repeated alerts and only notifies once when the temperature rises above and then drops back below the threshold.

If you have any problems, let me know and we'll fix it.
Currently, I don't have the ability to test it, but it should work.
Let me know if you need anything else

**Comment by LM1LC3N7** [comment]
Tested, works well as expected!
